/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geradorcaracteres;

/**
 *
 * @author efsantos
 */
public class GeradorCaracteres {

    /**
     * @param args the command line arguments
     */
    //teste
    public static String geraCaractere(char letra) {
        switch (letra) {
            case 'A':
                return "65";
            case 'B':
                return "66";
            case 'C':
                return "67";
            case 'D':
                return "68";
            case 'E':
                return "69";
            case 'F':
                return "70";
            case 'G':
                return "71";
            case 'H':
                return "72";
            case 'I':
                return "73";
            case 'J':
                return "74";
            case 'K':
                return "75";
            case 'L':
                return "76";
            case 'M':
                return "77";
            case 'N':
                return "78";
            case 'O':
                return "79";
            case 'P':
                return "80";
            case 'Q':
                return "81";
            case 'R':
                return "82";
            case 'S':
                return "83";
            case 'T':
                return "84";
            case 'U':
                return "85";
            case 'V':
                return "86";
            case 'W':
                return "87";
            case 'X':
                return "88";
            case 'Y':
                return "89";
            case 'Z':
                return "90";
            case 'a':
                return "97";
            case 'b':
                return "98";
            case 'c':
                return "99";
            case 'd':
                return "100";
            case 'e':
                return "101";
            case 'f':
                return "102";
            case 'g':
                return "103";
            case 'h':
                return "104";
            case 'i':
                return "105";
            case 'j':
                return "106";
            case 'k':
                return "107";
            case 'l':
                return "108";
            case 'm':
                return "109";
            case 'n':
                return "110";
            case 'o':
                return "111";
            case 'p':
                return "112";
            case 'q':
                return "113";
            case 'r':
                return "114";
            case 's':
                return "115";
            case 't':
                return "116";
            case 'u':
                return "117";
            case 'v':
                return "118";
            case 'w':
                return "119";
            case 'x':
                return "120";
            case 'y':
                return "121";
            case 'z':
                return "122";
            case 'Ç':
                return "128";
            case 'ü':
                return "129";
            case 'é':
                return "130";
            case 'â':
                return "131";
            case 'ä':
                return "132";
            case 'à':
                return "133";
            case 'å':
                return "134";
            case 'ç':
                return "135";
            case 'ê':
                return "136";
            case 'ë':
                return "137";
            case 'è':
                return "138";
            case 'ï':
                return "139";
            case 'î':
                return "140";
            case 'ì':
                return "141";
            case 'Ä':
                return "142";
            case 'Å':
                return "143";
            case 'É':
                return "144";
            case 'æ':
                return "145";
            case 'Æ':
                return "146";
            case 'ô':
                return "147";
            case 'ö':
                return "148";
            case 'ò':
                return "149";
            case 'û':
                return "150";
            case 'ù':
                return "151";
            case 'ÿ':
                return "152";
            case 'Ö':
                return "153";
            case 'Ü':
                return "154";
            case '¢':
                return "155";
            case '£':
                return "156";
            case '¥':
                return "157";
            case '₧':
                return "158";
            case 'ƒ':
                return "159";
            case 'á':
                return "160";
            case 'í':
                return "161";
            case 'ó':
                return "162";
            case 'ú':
                return "163";
            case 'ñ':
                return "164";
            case 'Ñ':
                return "165";
            case 'À':
                return "0192";
            case 'Á':
                return "0193";
            case 'Â':
                return "0194";
            case 'Ã':
                return "0195";
            case 'È':
                return "0200";

            case 'Ê':
                return "0202";
            case 'Ë':
                return "0203";
            case 'Ì':
                return "0204";
            case 'Í':
                return "0205";
            case 'Î':
                return "0206";
            case 'Ï':
                return "0207";
            case 'Ð':
                return "0208";

            case 'Ò':
                return "0210";
            case 'Ó':
                return "0211";
            case 'Ô':
                return "0212";
            case 'Õ':
                return "0213";

            case '×':
                return "0215";
            case 'Ø':
                return "0216";
            case 'Ù':
                return "0217";
            case 'Ú':
                return "0218";
            case 'Û':
                return "0219";

            case 'Ý':
                return "0221";
            case 'Þ':
                return "0222";
            case 'ß':
                return "0223";

            case 'ã':
                return "0227";

            case 'ð':
                return "0240";

            case 'õ':
                return "0245";

            case '÷':
                return "0247";
            case 'ø':
                return "0248";

            case 'ý':
                return "0253";
            case ' ':
                return "0160";
            case '#':
                return "35";
            case '$':
                return "36";
            case '%':
                return "37";
            case '&':
                return "38";
            case '\'':
                return "39";
            case '(':
                return "40";
            case ')':
                return "41";
            case '*':
                return "42";
            case '+':
                return "43";
            case ',':
                return "44";
            case '-':
                return "45";
            case '.':
                return "46";
            case '/':
                return "47";
            case '0':
                return "48";
            case '1':
                return "49";
            case '2':
                return "50";
            case '3':
                return "51";
            case '4':
                return "52";
            case '5':
                return "53";
            case '6':
                return "54";
            case '7':
                return "55";
            case '8':
                return "56";
            case '9':
                return "57";
            case ':':
                return "58";
            case ';':
                return "59";
            case '<':
                return "60";
            case '=':
                return "61";
            case '>':
                return "62";
            case '?':
                return "63";
            case '@':
                return "64";
        }
        return "Invalido";
    }

    public static String retornaCaracter(String numero) {

        switch (numero) {
            case "32":
                return " ";
            case "65":
                return "A";
            case "66":
                return "B";
            case "67":
                return "C";
            case "68":
                return "D";
            case "69":
                return "E";
            case "70":
                return "F";
            case "71":
                return "G";
            case "72":
                return "H";
            case "73":
                return "I";
            case "74":
                return "J";
            case "75":
                return "K";
            case "76":
                return "L";
            case "77":
                return "M";
            case "78":
                return "N";
            case "79":
                return "O";
            case "80":
                return "P";
            case "81":
                return "Q";
            case "82":
                return "R";
            case "83":
                return "S";
            case "84":
                return "T";
            case "85":
                return "U";
            case "86":
                return "V";
            case "87":
                return "W";
            case "88":
                return "X";
            case "89":
                return "Y";
            case "90":
                return "Z";
            case "97":
                return "a";
            case "98":
                return "b";
            case "99":
                return "c";
            case "100":
                return "d";
            case "101":
                return "e";
            case "102":
                return "f";
            case "103":
                return "g";
            case "104":
                return "h";
            case "105":
                return "i";
            case "106":
                return "j";
            case "107":
                return "k";
            case "108":
                return "l";
            case "109":
                return "m";
            case "110":
                return "n";
            case "111":
                return "o";
            case "112":
                return "p";
            case "113":
                return "q";
            case "114":
                return "r";
            case "115":
                return "s";
            case "116":
                return "t";
            case "117":
                return "u";
            case "118":
                return "v";
            case "119":
                return "w";
            case "120":
                return "x";
            case "121":
                return "y";
            case "122":
                return "z";
            case "128":
                return "Ç";
            case "129":
                return "ü";
            case "130":
                return "é";
            case "131":
                return "â";
            case "132":
                return "ä";
            case "133":
                return "à";
            case "134":
                return "å";
            case "135":
                return "ç";
            case "136":
                return "ê";
            case "137":
                return "ë";
            case "138":
                return "è";
            case "139":
                return "ï";
            case "140":
                return "î";
            case "141":
                return "ì";
            case "142":
                return "Ä";
            case "143":
                return "Å";
            case "144":
                return "É";
            case "145":
                return "æ";
            case "146":
                return "Æ";
            case "147":
                return "ô";
            case "148":
                return "ö";
            case "149":
                return "ò";
            case "150":
                return "û";
            case "151":
                return "ù";
            case "152":
                return "ÿ";
            case "153":
                return "Ö";
            case "154":
                return "Ü";
            case "155":
                return "¢";
            case "156":
                return "£";
            case "157":
                return "¥";
            case "158":
                return "P";
            case "159":
                return "ƒ";
            case "160":
                return "á";
            case "161":
                return "í";
            case "162":
                return "ó";
            case "163":
                return "ú";
            case "164":
                return "ñ";
            case "165":
                return "Ñ";
            case "0192":
                return "À";
            case "0193":
                return "Á";
            case "0194":
                return "Â";
            case "0195":
                return "Ã";
            case "0200":
                return "È";
            case "0202":
                return "Ê";
            case "0203":
                return "Ë";
            case "0204":
                return "Ì";
            case "0205":
                return "Í";
            case "0206":
                return "Î";
            case "0207":
                return "Ï";
            case "0208":
                return "Ð";
            case "0210":
                return "Ò";
            case "0211":
                return "Ó";
            case "0212":
                return "Ô";
            case "0213":
                return "Õ";
            case "0215":
                return "×";
            case "0216":
                return "Ø";
            case "0217":
                return "Ù";
            case "0218":
                return "Ú";
            case "0219":
                return "Û";
            case "0221":
                return "Ý";
            case "0222":
                return "Þ";
            case "0223":
                return "ß";
            case "0227":
                return "ã";
            case "0240":
                return "ð";
            case "0245":
                return "õ";
            case "0247":
                return "÷";
            case "0248":
                return "ø";
            case "0253":
                return "ý";
            case "0160":
                return " ";
            case "35":
                return "#";
            case "36":
                return "$";
            case "37":
                return "%";
            case "38":
                return "&";
            case "39":
                return "\\";
            case "40":
                return "(";
            case "41":
                return ")";
            case "42":
                return "*";
            case "43":
                return "+";
            case "44":
                return ",";
            case "45":
                return "-";
            case "46":
                return ".";
            case "47":
                return "/";
            case "48":
                return "0";
            case "49":
                return "1";
            case "50":
                return "2";
            case "51":
                return "3";
            case "52":
                return "4";
            case "53":
                return "5";
            case "54":
                return "6";
            case "55":
                return "7";
            case "56":
                return "8";
            case "57":
                return "9";
            case "58":
                return ":";
            case "59":
                return ";";
            case "60":
                return "<";
            case "61":
                return "=";
            case "62":
                return ">";
            case "63":
                return "?";
            case "64":
                return "@";
            default:
                return numero;
        }
    }

}
